### PR TITLE
Feat #ob locale route

### PR DESCRIPTION
**Pull request by henrikaskj**
Add optional locale parameter for better pre rendering and SEO of non-norwegian pages

### CODE REVIEW

**Review by sawravchy — APPROVED** [review]
Seems like It is ready for the merge now but I have encountered the article rerender issue with the language change @henrikaskj

**Comment by henrikaskj** [comment]
> Seems like It is ready for the merge now but I have encountered the article rerender issue with the language change @henrikaskj

What issue was this?

**Comment by sawravchy** [comment]
> > Seems like It is ready for the merge now but I have encountered the article rerender issue with the language change @henrikaskj
> 
> What issue was this?

Articles JSON data are re-fetching with the language change which may cause extra memory.

**Comment by henrikaskj** [comment]
> > > Seems like It is ready for the merge now but I have encountered the article rerender issue with the language change @henrikaskj
> > 
> > 
> > What issue was this?
> 
> Articles JSON data are re-fetching with the language change which may cause extra memory.

It's because of the navigation. Turns out it's a more general issue with re-fetching that shouldn't happen, that we apparently have had for a long time. I'll look into it.

**Comment by henrikaskj** [comment]
> > > > Seems like It is ready for the merge now but I have encountered the article rerender issue with the language change @henrikaskj
> > > 
> > > 
> > > What issue was this?
> > 
> > 
> > Articles JSON data are re-fetching with the language change which may cause extra memory.
> 
> It's because of the navigation. Turns out it's a more general issue with re-fetching that shouldn't happen, that we apparently have had for a long time. I'll look into it.

I tested it in a bare nuxt project, and apparently the requests are always sent if the route parameters change. We can prevent re-render though, so that we avoid the flickering.

**Comment by sawravchy** [comment]
> > > > > Seems like It is ready for the merge now but I have encountered the article rerender issue with the language change @henrikaskj
> > > > 
> > > > 
> > > > What issue was this?
> > > 
> > > 
> > > Articles JSON data are re-fetching with the language change which may cause extra memory.
> > 
> > 
> > It's because of the navigation. Turns out it's a more general issue with re-fetching that shouldn't happen, that we apparently have had for a long time. I'll look into it.
> 
> I tested it in a bare nuxt project, and apparently the requests are always sent if the route parameters change. We can prevent re-render though, so that we avoid the flickering.

Yes. I think it will be better for us if we can avoid this.

**Pull request merged**
